name: deployment

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Extract version from tag
      run: echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Pack with tag version
      run: dotnet pack ./src/BetfairDotNet/BetfairDotNet.csproj --configuration Release -o ./out /p:Version=${{ env.PACKAGE_VERSION }}
  
    - name: Push to NuGet
      run: dotnet nuget push "./out/BetfairDotNet.*.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
